#!/bin/bash

JENKINS_USER_HOME_DIRECTORY=/var/lib/jenkins
JENKINS_PROPERTIES_DIRECTORY=$JENKINS_USER_HOME_DIRECTORY/pipelines-configuration/properties
JENKINS_ONCOTREE_PROPERTIES_DIRECTORY=$JENKINS_PROPERTIES_DIRECTORY/oncotree

# ONCOTREE_DIRECTORY is starting directory - location on jenkins machine where github repo is cloned
ONCOTREE_DIRECTORY="$(pwd)"
JENKINS_TEST_APPLICATION_PROPERTIES=jenkins.test.application.properties

APPLICATION_PROPERTIES=application.properties
TEST_APPLICATION_PROPERTIES=test.application.properties

rsync $JENKINS_ONCOTREE_PROPERTIES_DIRECTORY/$JENKINS_TEST_APPLICATION_PROPERTIES $ONCOTREE_DIRECTORY/web/src/main/resources/$APPLICATION_PROPERTIES
rsync $JENKINS_ONCOTREE_PROPERTIES_DIRECTORY/$TEST_APPLICATION_PROPERTIES $ONCOTREE_DIRECTORY/core/src/test/resources/$APPLICATION_PROPERTIES
