name: ESLint
on: [push, pull_request]
jobs: 
  build:
    defaults:
        run:
          working-directory: web/src/main/javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: pnpm
          cache-dependency-path: web/src/main/javascript/pnpm-lock.yaml
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm run lint